### PR TITLE
1.13 Support

### PR DESCRIPTION
**Pull request by Redned235**

### CODE REVIEW

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/aacd81343aff72293ff1ad0ccaa8cd8a87d66836#diff-13909a8b0c0715c6531a28480b7bbcc1R2
https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/aacd81343aff72293ff1ad0ccaa8cd8a87d66836#diff-13909a8b0c0715c6531a28480b7bbcc1R164

In the imports, we see that WorldEdit has changed from `worldedit.Vector` to `worldedit.math.BlockVector3`

So, on line 165 of the WorldGuardInterface, the method signature of pasteSchematic() should change completely...

Instead of accepting `BlockVector3 position`, we should accept our own `mc.alk.arena.plugins.worldedit.math.BlockVector` (for example)... Then, whenever WorldEdit requires this information, we convert from our `BlockVector` to whatever they need:  Either `Vector` or `BlockVector3`

^The class name & package location can be whatever we want:  `mc.alk.arena.plugins.worldedit.math.BlockVector`  is just an example.

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/aacd81343aff72293ff1ad0ccaa8cd8a87d66836#diff-613789aad080b97d9f57b7bb004285feR127

`WorldGuardAbstraction` lines 128, 129, 130:
https://github.com/BattlePlugins/WorldEditUtil/blob/aacd81343aff72293ff1ad0ccaa8cd8a87d66836/modules/api/src/main/java/mc/alk/arena/plugins/worldguard/WorldGuardAbstraction.java#L112
https://github.com/BattlePlugins/WorldEditUtil/blob/aacd81343aff72293ff1ad0ccaa8cd8a87d66836/modules/api/src/main/java/mc/alk/arena/plugins/worldguard/WorldGuardAbstraction.java#L108

It looks like these methods need to be deleted from `WorldGuardAbstraction` and the implementation details from `createRegion()` needs to move to `v5.WG`, `v6.WG`, & `v7.WG` with an unfortunate `returns null;` for the `v0.WG` implementation.

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/bea131a83922179d716beed334396edc6f56fefa
All the comments are wrong here when you changed all occurrences of `v6` to `v7` ...which isn't a big deal except on line 170 of `v7.WG`:
https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/bea131a83922179d716beed334396edc6f56fefa#diff-38269d6b7385388129adf4a04e7fea37R168
https://github.com/BattlePlugins/WorldEditUtil/blob/bea131a83922179d716beed334396edc6f56fefa/modules/v7/src/main/java/mc/alk/arena/plugins/worldguard/v7/WG.java#L170

This comment on line 170 should be corrected or deleted.

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/7e97b9162de92f050073d3ecd8a8ed037a974d17

Whoa, there's a lot to go over here...  I don't have enough time this second to go over everything, but I can comment on some things that stood out the most:

https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/7e97b9162de92f050073d3ecd8a8ed037a974d17#diff-2cbd9f792f965dda604cc584ef4372dfL23
This doesn't need to change in order to update to 1.13 because Bukkit is the interface.  Only Craftbukkit implementations have to update to 1.13.

https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/7e97b9162de92f050073d3ecd8a8ed037a974d17#diff-2c63ffa8d31b2a88504bda851b963efaL2
Import changes:  Same deal.  Need an intermediary class.
BattleArena doesn't use this.  This is used by ArenaSpleef.  So this change in WorldEdit & WorldEditUtil break that plugin.

https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/7e97b9162de92f050073d3ecd8a8ed037a974d17#diff-613789aad080b97d9f57b7bb004285feL2
`WorldGuardAbstraction` cannot be changed in this way... If any changes need to happen to this class, then it should be deleted and changed in v0, v5, v6, & v7.WG

https://github.com/BattlePlugins/WorldEditUtil/pull/1/commits/7e97b9162de92f050073d3ecd8a8ed037a974d17#diff-13909a8b0c0715c6531a28480b7bbcc1R66
We shouldn't have to delete the entire `modules/v5` as the whole point of the `WorldEditUtil` library is for BattleArena to be able to support many different versions of WorldEdit/WorldGuard... And have the server Admins choose which version they want to use.

`WorldGuardInterface.newInstance()` should look something like this:

```
public static WorldGuardInterface newInstance() {
        WorldGuardInterface WGI = null;
        Version<Plugin> we = VersionFactory.getPluginVersion("WorldEdit");
        Version<Plugin> wg = VersionFactory.getPluginVersion("WorldGuard");
        WorldGuardPlugin wgp = (WorldGuardPlugin) Bukkit.getPluginManager().getPlugin("WorldGuard");
        boolean wgIsInitialized = FieldTester.isInitialized(wgp);
        if (we.isCompatible("7") && wg.isCompatible("7") && wgIsInitialized) {
            WGI = instantiate("v7");
        } else if (we.isCompatible("6") && we.isLessThan("7") && wg.isCompatible("6") && wg.isLessThan("7")&& wgIsInitialized) {
            WGI = instantiate("v6");
        } else if (we.isCompatible("5") && we.isLessThan("6") && wg.isCompatible("5") && wg.isLessThan("6")&& wgIsInitialized) {
            WGI = instantiate("v5");
        } else {
            // Not present, not compatible, or not supported.
            System.out.println("[BattleArena] WG/WE not present, not compatible, or not supported.");
            WGI = instantiate("v0");
        }
        return WGI;
    }
```
Sorry, I ran out of time for now.  I'll look thru more of this & your other pull requests later.

I noticed that the `mc.euro.version` imports were wrong, but that's not something that you can fix (long explanation)... This is kinda me talking to myself that I need to fix that ! lol

Thanks for helping with BattleArean btw !

**Comment by Redned235** [comment]
Thanks for all the improvement suggestions. I’ve worked on a few of these changes and I’ll commit them once I do a bit more testing.

**Pull request closed without merging**
